name: Build and Deploy Client to GH Pages
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Install and Build 🔧 
        run: |
          npm ci
          REACT_APP_REAL_SERVER_BASE=https://api.vaxx.link/api npm run build
      - name: Build example viewer
        working-directory: ./shl-client
        run: |
          npm ci
          npm run build
          cp -r dist ../build/viewer
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
