name: Deploy vaxx.link server
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ fromJSON(secrets.AZURE_CREDENTIALS_21).appId }}
        password: ${{ fromJSON(secrets.AZURE_CREDENTIALS_21).password }}

    - uses: azure/aks-set-context@v2
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS_21 }}'
        cluster-name: ${{ secrets.CLUSTER_NAME_21 }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Build and rollout to CI
      working-directory: ./server
      run: |
        docker build . \
          -t ${{ secrets.CONTAINER_REGISTRY }}/vaxxlink:$GITHUB_SHA \
          -t ${{ secrets.CONTAINER_REGISTRY }}/vaxxlink:latest
        docker push ${{ secrets.CONTAINER_REGISTRY }}/vaxxlink
        kubectl -n smart rollout restart deployment/vaxxlink
